title: TIITLEE
author: GSimas
email: thisismyemail@email.com
description: this is a description of my website. Feel free to read it

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
